##
## Autogenerated by genvarmod.py
##

variable "ace_keyvault_linked_certificate_id" {
  type        = string
  description = "ID of the linked certificate in Azure Key Vault used for securing resources in the infrastructure deployment."
}

variable "app_dns_name" {
  type        = string
  description = "Specifies the DNS name for the application to enable access and routing in the cloud infrastructure."
}

variable "container_app_environment_id" {
  type        = string
  description = "ID of the container app environment used to deploy and manage containerized applications in the infrastructure."
}

variable "container_app_environment_name" {
  type        = string
  description = "Specifies the name of the container app environment for deploying applications in the infrastructure setup."
}

variable "container_app_environment_resource_group" {
  type        = string
  description = "Specifies the resource group for the Azure Container App environment in the infrastructure setup."
}

variable "container_app_id" {
  type        = string
  description = "Unique identifier for the container app used to manage and reference the application in the infrastructure setup."
}

variable "container_app_name" {
  type        = string
  description = "Specifies the name of the container application to be deployed in the infrastructure setup."
}

variable "dns_zone_name" {
  type        = string
  description = "Specifies the name of the DNS zone to be created or managed in the cloud infrastructure."
}

variable "domain_zone_resource_group_name" {
  type        = string
  description = "Specifies the resource group name where the domain zone resources are managed in the cloud infrastructure."
}

variable "environment_suffix" {
  type        = string
  description = "Suffix used to distinguish resources in different environments such as dev, test, or production for better organization."
}

variable "environment_tag" {
  type        = string
  description = "Tag to identify the deployment environment such as development, staging, or production for resource organization."
}

variable "warning_tag" {
  type        = string
  description = "Tag used to identify resources that require attention or caution within the infrastructure deployment."
}

